services:
  redis:
    image: redis:alpine
    command: [ redis-server, --maxmemory 128mb, --maxmemory-policy volatile-lru, --save "" ]

  rabbitmq:
    image: rabbitmq:alpine
    volumes:
      - pimcore-rabbitmq:/var/lib/rabbitmq/

  db:
    image: mariadb:10.11
    working_dir: /application
    command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_520_ci, --innodb-file-per-table=1 ]
    volumes:
      - pimcore-database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h db -u$$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e 'SHOW TABLES;'" ]
      interval: 10s
      retries: 6
      start_period: 1m
      timeout: 3s

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./pimcore:/var/www/html:ro
      - ./pimcore/.docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pimcore.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.pimcore.entrypoints=websecure"
      - "traefik.http.routers.pimcore.tls.certresolver=le"
      - "traefik.http.services.pimcore.loadbalancer.server.port=80"
    depends_on:
      - php

  php:
    user: "${UID}:${GID}"
    image: pimcore/pimcore:php8.3-debug-latest
    environment:
      working_dir: /var/www/html
      COMPOSER_CACHE_DIR: /composer/cache
      PHP_IDE_CONFIG: serverName=localhost

      PIMCORE_INSTALL_ADMIN_USERNAME: ${PIMCORE_ADMIN_USERNAME}
      PIMCORE_INSTALL_ADMIN_PASSWORD: ${PIMCORE_ADMIN_PASSWORD}

      PIMCORE_INSTALL_MYSQL_USERNAME: ${MYSQL_USER}
      PIMCORE_INSTALL_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PIMCORE_INSTALL_MYSQL_PORT: 3306
      PIMCORE_INSTALL_MYSQL_HOST_SOCKET: db
      PIMCORE_INSTALL_MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./pimcore:/var/www/html
      - ./pimcore/.docker/messenger.yaml:/var/www/html/config/packages/messenger.yaml:ro
      - ./pimcore/.docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - composer-cache:/composer/cache

  supervisord:
    user: "${UID}:${GID}"
    image: pimcore/pimcore:php8.3-supervisord-latest
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./pimcore:/var/www/html
      - ./pimcore/.docker/messenger.yaml:/var/www/html/config/packages/messenger.yaml:ro
      - ./pimcore/.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./letsencrypt:/letsencrypt
      # Automatische Pfaderkennung:
      - ${CERT_PATH_WSL}:/etc/traefik/certs:ro
      - ${CERT_PATH_WIN}:/etc/traefik/certs:ro
    restart: unless-stopped

  test-db:
    profiles: [ 'test' ]
    extends: db
    volumes:
      - pimcore-test-database:/var/lib/mysql

  test-php:
    profiles: [ 'test' ]
    extends: php
    environment:
      APP_ENV: test
      PIMCORE_TEST_DB_DSN: ${PIMCORE_TEST_DB_DSN:-mysql://pimcore:pimcore@test-db/pimcore}
      PIMCORE_INSTALL_ADMIN_USERNAME: pimcore
      PIMCORE_INSTALL_ADMIN_PASSWORD: pimcore
      PIMCORE_INSTALL_MYSQL_HOST_SOCKET: test-db
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - pimcore-test-var:/var/www/html/var
      - pimcore-test-public-var:/var/www/html/public/var

volumes:
  pimcore-database:
  pimcore-rabbitmq:
  pimcore-test-database:
  pimcore-test-var:
  pimcore-test-public-var:
